version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
- package-ecosystem: maven
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
- package-ecosystem: docker-compose
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
